version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Spring Boot application..."
      - cd m3project/
      - ./mvnw clean package
  post_build:
    commands:
      - echo "Project deployed."

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "/root/.m2/**/*"
