version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Running tests..."
  post_build:
    commands:
      - echo "Project deployed."

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - node_modules/
