version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: docker_credentials:dockerhub_username
    DOCKERHUB_PASSWORD: docker_credentials:dockerhub_password

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo "Building Spring Boot application..."
      - cd m3project/
      - ./mvnw clean package
      - echo "Retrieving Docker registry credentials..."
      - docker build -t afawafa/mod4-project-docker:latest .
      - echo "Pushing Docker image to registry..."
      - docker push afawafa/mod4-project-docker:latest
  post_build:
    commands:
      - echo "Project deployed."

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "/root/.m2/**/*"
